apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 75-rhcos4-moderate-master-auditd-name-format.yaml
- 75-rhcos4-moderate-master-audit-rules-dac-modification-chmod.yaml 
- cli-sa.yaml
- cli-sa-rbac.yaml
- cli-job-master.yaml
- cli-job-worker.yaml
