apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  ## "namespace" omitted since ClusterRoles are not namespaced
  name: machineconfig-cluster-role
Rules:
  ## Specifies core api groups
- apiGroups: ["machineconfiguration.openshift.io"] 
  resources: ["machineconfigs"]
  verbs: ["*"]
