apiVersion: rbac.authorization.k8s.io/v1
 ## Allows ArgoCD Service Account to interact with MachineConfigs
kind: ClusterRoleBinding
metadata:
  name: argocd-cluster-openshift-gitops-machineconfig
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
   ## Name of cluster role to be referenced
  name: machineconfig-cluster-role 
subjects:
- kind: ServiceAccount
  name: argocd-cluster-argocd-application-controller
  namespace: openshift-gitops 

