apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-container-security
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/container-security-operator/base
    repoURL: https://github.com/beelandc/openshift4-gitops-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  sync:
    comparedTo:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      source:
        path: manifests/container-security-operator/base
        repoURL: https://github.com/beelandc/openshift4-gitops-demo
        targetRevision: main
