apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-app
spec:
  destination:
    namespace: pricelist
    server: https://kubernetes.default.svc
  project: pricelist
  source:
    path: manifests/pricelist/
    repoURL: https://github.com/beelandc/openshift4-gitops-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: pricelist
        server: https://kubernetes.default.svc
      source:
        path: manifests/pricelist/
        repoURL: https://github.com/beelandc/openshift4-gitops-demo
        targetRevision: main
