apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-sealed-secrets
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/sealed-secrets/base
    repoURL: https://github.com/beelandc/openshift4-gitops-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: sealed-secrets
        server: https://kubernetes.default.svc
      source:
        path: manifests/sealed-secrets/base
        repoURL: https://github.com/beelandc/openshift4-gitops-demo
        targetRevision: main
