apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "OpenShift Operators"
    openshift.io/display-name: "Openshift Operators"
    argocd.argoproj.io/sync-wave: "0"
  name: openshift-operators
