apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh-stable-redhat-operators-openshift-marketplace
  namespace: openshift-operators
spec:
  channel: stable
  config:
    resources: {}
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: redhat-openshift-pipelines.v1.3.1
